ifeq "$(PLATFORM)" "mingw32"
LIBS+=-static -lgcc
endif

all: $(TARGET)

%.o: %.cpp
	$(CXX) $(CXXFLAGS) $(SHRFLAGS) -c $<

$(TARGET): $(OBJS)
	$(CXX) $(OPTS) $(SHRFLAGS) -o $@ $(OBJS) $(LDFLAGS) $(LIBS)

clean:
	rm -f $(OBJS)

distclean: clean
	rm -f $(TARGET)

